(function(){
  var cs=new CSInterface(),$=function(id){return document.getElementById(id);};
  var panelPath=decodeURI(window.location.pathname).replace(/\\/g,"/");if(/^\/[A-Za-z]:\//.test(panelPath)){panelPath=panelPath.substring(1);}
  var hostPath=panelPath.replace(/\/client\/index\.html(?:[?#].*)?$/i,"")+"/host/MOParkRuntime.jsx";
  var phase="in",direction="up",timer=null,frameRate=30;
  var settings={"in":{direction:"up",distance:100,duration:30,ease:100,scaleOn:false,scale:80,opacityOn:false},"out":{direction:"up",distance:100,duration:30,ease:-100,scaleOn:false,scale:80,opacityOn:false}};
  var presets=[];try{presets=JSON.parse(localStorage.getItem("moParkPresets")||"[]");}catch(ignore){presets=[];}
  function callHost(code,cb){$("status").textContent="Working...";cs.evalScript('$.evalFile("'+hostPath+'");'+code,function(r){if(cb){cb(r);}else{$("status").textContent=r;}});}
  function timing(e){var n=Math.max(-1,Math.min(1,e/100));if(n>=0){return "cubic-bezier(.16,1,"+(0.3-0.2*n)+",1)";}return "cubic-bezier("+(0.7+0.25*(-n))+",0,.84,0)";}
  function vector(dir,n){if(dir==="up")return "translateY("+(phase==="in"?n:-n)+"px)";if(dir==="down")return "translateY("+(phase==="in"?-n:n)+"px)";if(dir==="left")return "translateX("+(phase==="in"?n:-n)+"px)";if(dir==="right")return "translateX("+(phase==="in"?-n:n)+"px)";return "translate(0,0)";}
  function save(){var s=settings[phase];s.direction=direction;s.distance=Number($("distance").value);s.duration=Number($("duration").value);s.ease=Number($("ease").value);s.scaleOn=$("scaleOn").checked;s.scale=Number($("scale").value);s.opacityOn=$("opacityOn").checked;}
  function load(){var s=settings[phase];direction=s.direction;$("distance").value=s.distance;$("duration").value=s.duration;$("ease").value=s.ease;$("scaleOn").checked=s.scaleOn;$("scale").value=s.scale;$("opacityOn").checked=s.opacityOn;setButtons("direction","data-direction",direction);refresh();}
  function refresh(){clearTimeout(timer);save();refreshOutputs();var s=settings[phase],move=vector(s.direction,s.distance*.45),scale=s.scaleOn?" scale("+(s.scale/100)+")":"",obj=$("object");obj.style.setProperty("--from",move+scale);obj.style.setProperty("--to",move+scale);obj.style.setProperty("--opacity-from",s.opacityOn?"0":"1");obj.style.setProperty("--opacity-to",s.opacityOn?"0":"1");obj.style.animation="none";void obj.offsetWidth;obj.style.animation=(phase==="in"?"parkIn":"parkOut")+" "+Math.max(.2,s.duration/frameRate)+"s "+timing(s.ease)+" both";timer=setTimeout(refresh,Math.max(900,s.duration/frameRate*1000+500));}
  function refreshOutputs(){$("distanceOut").textContent=$("distance").value+" px";$("durationOut").textContent=$("duration").value+" fr";$("easeOut").textContent=$("ease").value+"%";$("scaleOut").textContent=$("scale").value+"%";$("scaleRow").style.display=$("scaleOn").checked?"block":"none";}
  function setButtons(group,attr,value){var b=$(group).getElementsByTagName("button");for(var i=0;i<b.length;i++){b[i].className=b[i].getAttribute(attr)===value?"active":"";}}
  function bindButtons(group,attr,fn){var b=$(group).getElementsByTagName("button");for(var i=0;i<b.length;i++){b[i].onclick=function(){fn(this.getAttribute(attr));};}}
  function esc(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
  function directionName(n){return ["","Up","Down","Left","Right","None"][Math.round(n)]||"None";}
  function block(label,p,side){if(!p.enabled)return "";var lines='<div class="preset-phase">'+label+'</div><div class="preset-line">'+p.duration+' fr · Ease '+p.ease+'%</div>';if(p.positionEnabled)lines+='<div class="preset-line">Position '+directionName(p.direction)+' · '+p.distance+' px</div>';if(p.scaleEnabled)lines+='<div class="preset-line">Scale '+p.scale+'%</div>';if(p.opacityEnabled)lines+='<div class="preset-line">Opacity</div>';return '<div class="preset-block '+side+'">'+lines+'</div>';}
  function renderPresets(){var box=$("presetLibrary"),html="";for(var i=0;i<presets.length;i++){var p=presets[i],continuous="";if(p.continuous&&p.continuous.enabled){continuous='<div class="preset-line">Continuous'+(p.continuous.positionEnabled?' · Position '+directionName(p.continuous.direction)+' '+p.continuous.positionSpeed+' px/s':'')+(p.continuous.scaleEnabled?' · Scale '+p.continuous.scaleSpeed+' %/s':'')+'</div>';}html+='<div class="preset-card"><div class="preset-title">'+esc(p.name)+'</div><button class="preset-delete" data-delete="'+i+'">×</button><div class="preset-columns">'+block("IN",p["in"],"in")+block("OUT",p["out"],"out")+'</div>'+continuous+'<button class="preset-apply" data-apply="'+i+'">Apply</button></div>';}box.innerHTML=html;var del=box.getElementsByClassName("preset-delete");for(i=0;i<del.length;i++)del[i].onclick=function(){presets.splice(Number(this.getAttribute("data-delete")),1);persist();renderPresets();};var apply=box.getElementsByClassName("preset-apply");for(i=0;i<apply.length;i++)apply[i].onclick=function(){var p=presets[Number(this.getAttribute("data-apply"))];callHost('MOParkApplySavedPreset("'+encodeURIComponent(JSON.stringify(p))+'")');};}
  function persist(){try{localStorage.setItem("moParkPresets",JSON.stringify(presets));}catch(ignore){}}
  bindButtons("mainTabs","data-view",function(v){setButtons("mainTabs","data-view",v);$("createView").style.display=v==="create"?"block":"none";$("libraryView").style.display=v==="library"?"block":"none";if(v==="library")renderPresets();});
  bindButtons("phase","data-phase",function(v){save();phase=v;setButtons("phase","data-phase",v);$("apply").textContent="Apply "+v.toUpperCase();load();});
  bindButtons("direction","data-direction",function(v){direction=v;setButtons("direction","data-direction",v);refresh();});
  bindButtons("anchor","data-anchor",function(v){setButtons("anchor","data-anchor",v);var p=v.split(",");callHost("MOParkSetAnchor("+p[0]+","+p[1]+")");});
  ["distance","duration","ease","scale","scaleOn","opacityOn"].forEach(function(id){$(id).addEventListener("input",refresh);$(id).addEventListener("change",refresh);});
  $("apply").onclick=function(){save();var s=settings[phase];callHost('MOParkApplyPhase("'+phase+'","'+s.direction+'",'+s.distance+','+s.duration+','+s.ease+','+(s.scaleOn?1:0)+','+s.scale+','+(s.opacityOn?1:0)+')');};
  $("clean").onclick=function(){callHost("MOParkClear()");};
  $("saveLayerPreset").onclick=function(){var name=$("presetName").value.replace(/^\s+|\s+$/g,"");if(!name){$("status").textContent="Enter a preset name first.";return;}callHost("MOParkReadSelectedLayer()",function(r){try{var p=JSON.parse(r);if(p.error){$("status").textContent=p.error;return;}p.name=name;presets.push(p);persist();renderPresets();$("presetName").value="";$("status").textContent=name+" saved from selected layer.";}catch(e){$("status").textContent="Could not read selected layer: "+r;}});};
  $("authorLink").onclick=function(e){e.preventDefault();var u="https://www.instagram.com/brunojorri_work/";if(window.cep&&window.cep.util){window.cep.util.openURLInDefaultBrowser(u);}else{window.open(u,"_blank");}};
  renderPresets();load();callHost("MOParkGetFrameRate()",function(r){var n=Number(r);if(n>0)frameRate=n;$("status").textContent="Select one 2D layer in After Effects.";refresh();});
}());
